[build]
  publish = "."
  command = "echo 'No build required - static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noai, noimageai"
    X-Copyright = "Protected content"

[[redirects]]
  from = "/OrbitalPort.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/portfolio.html"
  to = "/"
  status = 301