[build]
  publish = "."
  command = "echo 'No build required - static site'"

[build.environment]
  NODE_VERSION = "18"



[[redirects]]
  from = "/OrbitalPort.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/portfolio.html"
  to = "/"
  status = 301